### ISSUE TITLE
Does not plot due to error "cannot find arrow() function"

### ISSUE THREAD

**Issue by schmidtchristoph** [briatte/ggnet#11]
Dear François,

thank you for the really nice network plotting function. Unfortunately the code broke during one of the last commits so that plotting does not work anymore. The following example is taken from the examples listed in the ggnet2 documentation and produces the error:

start R
library(ggnet)

  x           <- 10
  ndyads      <- x * (x - 1)
  density     <- x / ndyads
  m           <- matrix(0, nrow = x, ncol = x)
  dimnames(m) <- list(letters[ 1:x ], letters[ 1:x ])
  m[ row(m) != col(m) ] <- runif(ndyads) < density
  m

  # random undirected network
  n <- network::network(m, directed = FALSE)
  n

  ggnet2(n, label = TRUE)

I cloned your repository, fixed this and other problems and will submit a pull request.

Best,
Christoph

**Comment by briatte** [comment]
Hi @schmidtchristoph 

Thanks for the issue report and pull request.

The error is due to your version of `ggplot2`, which is probably the CRAN one. Install the forthcoming version of `ggplot2` to get rid of the error:

```r
devtools::install_github("hadley/ggplot2")
```

That version should land on CRAN in the near future.
