### ISSUE TITLE
could not find function "arrow"

### ISSUE THREAD

**Issue by vikasrawal** [briatte/ggnet#15]
Why am I getting this error?

> net = rgraph(10, mode = "graph", tprob = 0.5)
> net = network(net, directed = FALSE)
> network.vertex.names(net) = letters[1:10]
> ggnet(net)
Error in do.call("layer", list(mapping = mapping, data = data, stat = stat,  : 
  could not find function "arrow"

**Comment by briatte** [comment]
For clarity: this error was probably due to your versions of the `ggplot2` and/or `scales` packages. The example works fine with the current latest versions.

I'll update the `README` of the repository, it's outdated right now.
