### ISSUE TITLE
ggnet2: argument `arrow.gap` introduces shifting of the edges

### ISSUE THREAD

**Issue by grigory93** [briatte/ggnet#17]
Network plot without arrows:

``` r
net = network(rgraph(10, tprob = 0.25), directed = TRUE)
ggnet2(net)
```

![image](https://cloud.githubusercontent.com/assets/5093758/14405709/ed9e0368-fe59-11e5-9e99-9c657756d648.png)
After adding arrows with `arrow.size`:

``` r
ggnet2(net, arrow.size = 20)
```

![image](https://cloud.githubusercontent.com/assets/5093758/14405715/25587342-fe5a-11e5-905a-34da6b41a724.png)
Observe shifting of the edges or similar questionable effect after adding `arrow.gap` only: 

``` r
ggnet2(net, arrow.size = 20, arrow.gap = 0.05)
```

![image](https://cloud.githubusercontent.com/assets/5093758/14405702/c91d089a-fe59-11e5-9a6f-c7523b0cf1e1.png)

Running with **GGally 1.0.1, ggplot2 2.1.0, grid 3.4.0**

**Comment by briatte** [comment]
Interesting bug, thanks. Arrows are a pain to draw (somewhat) properly.

May I recommend that you try [`ggnetwork`](https://github.com/briatte/ggnetwork) to see if that helps? The syntax should also be a bit more intuitive if you know `ggplot2`.

**Comment by aterhorst** [comment]
I experienced the same issue with `arrow.gap`. I did try `ggnetwork` as suggested but this requires a lot more hacking to get to work. I think `ggnet2` is easier/nicer to use for quick plots. I hope you get around to fixing this bug! Many thanks for the great work.

**Comment by aterhorst** [comment]
I do not know where to set arrow.gap in `ggnetwork`. Please advise.

**Comment by rbirkelbach** [comment]
I also have this bug. I'm using the most recent version.

**Comment by briatte** [comment]
@grigory93 @aterhorst @rbirkelbach – the bug has been fixed by myself within `ggnet`, and by @heike within `GGally` (thanks!).

To use immediately, you can either use `ggnet` instead of `GGally`, or install `GGally` from GitHub:

``` R
library(devtools)
install_github("briatte/ggnet") # or
install_github("ggobi/ggally")
```

The `GGally` should soon be updated to fix the bug after which you should be able to install it from CRAN and not see the bug anymore.

Sorry for the slow reply to all.

**Comment by aterhorst** [comment]
Thanks. The issue has been fixed! One thing though, when I plot multiple graphs side by side using mode = c("x","y") as per vignette, the arrows disappear.

library(randomcoloR)
n <- 23 # number of employers (varies)
col.scale <- distinctColorPalette(n)

x = gplot.layout.fruchtermanreingold(knowledge.provider.net.sna, NULL)
knowledge.provider.net.sna %v% "x" = x[, 1]
knowledge.provider.net.sna %v% "y" = x[, 2]
idea.generation.net.sna %v% "x" = x[, 1]
idea.generation.net.sna %v% "y" = x[, 2]

p1 <- ggnet2(knowledge.provider.net.sna, mode = c("x","y"), color = "employer", arrow.size = 10, arrow.gap = 0.0135, palette = col.scale, node.size = 10, label = "vertex.id", edge.color = "grey")
p2 <- ggnet2(idea.generation.net.sna, mode = c("x","y"), color = "employer", arrow.size = 10, arrow.gap = 0.0135, palette = col.scale, node.size = 10, label = "vertex.id", edge.color = "grey")

# common plotting parameters
b = theme(panel.background = element_rect(color = "grey50"))
z = guides(color = FALSE)
y = scale_y_continuous(limits = range(x[, 2] * 1.1), breaks = NULL)
x = scale_x_continuous(limits = range(x[, 1] * 1.1), breaks = NULL)

# plot networks in a grid layout
gridExtra::grid.arrange(p1 + x + y + z + ggtitle("knowledge provider") + b,
                        p2 + x + y + z + ggtitle("idea generation") + b,
                        nrow = 1)
