### ISSUE TITLE
Isolates appearing in graphs with all nodes of degree >= 30

### ISSUE THREAD

**Issue by khanna7** [briatte/ggnet#19]
I am plotting a network where nodes with degree of at least 30 have been preselected. Yet the plot shows several isolates. How can that be?

``` r
summary(r0_net %v% "degree")
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   30.0    38.0    52.0   403.8   493.0  4729.0 

  pdf(file="ggnet-ex.pdf")
  ggnet2(r0_net, color="color", size=2)
  dev.off()
```

[ggnet-ex.pdf](https://github.com/briatte/ggnet/files/273679/ggnet-ex.pdf)

**Comment by khanna7** [comment]
This problem was with the data, not the program. Please ignore.

**Comment by briatte** [comment]
May I recommend that you give a try to [ggnetwork](https://cran.r-project.org/web/packages/ggnetwork/index.html)? It's more powerful than ggnet2, and even closer to ggplot2 syntax.
