### ISSUE TITLE
arranging plots in a grid

### ISSUE THREAD

**Issue by khanna7** [briatte/ggnet#20]
Hello,

I have used 'ggnet' to show the evolution of the networks of two nodes over three waves here: http://rpubs.com/khanna7/183807

I am looking for ideas on how to arrange these nicely in a grid. If you have some ideas, please let me know.

Thank you,
Aditya Khanna

**Comment by briatte** [comment]
Hi @khanna7 

If you want the same nodes shown in each wave, then the [node faceting](https://briatte.github.io/ggnetwork/#node-faceting) functionality of `ggnetwork` will work better for you than any possible hack with `ggnet`, which is more limited.

Please give `ggnetwork` a try and let me know what you think!
