### ISSUE TITLE
Restriction on Edge Labels

### ISSUE THREAD

**Issue by erdogancevher** [briatte/ggnet#21]
Edge labels are centered. Not possible to enter 2 edge labels on the same arrow. 
This is needed: 
For example, in Network Topology of causal relationships in a VAR model, it is customary to write the p values of the G-causalities on the same arrow; one is to indicate the GC from variable A to variable B, and the other is from variable B to variable A. 

It seemed impossible to me to construct such a needed graph with ggnet.

Example (the graphs to be drawn Needed, but not Possible with ggnet)
Figure 3 here: https://www.academia.edu/17057780/Determinants_of_Current_Account_Deficit_in_Turkey_The_Conditional_and_Partial_Granger_Causality_Approach

Note that 2 labels are needed (one at the beginning and the other at the end of the same arrow).

**Comment by briatte** [comment]
Hi @erdogancevher 

You are correct, `ggnet` is not flexible enough to have two labels per edge, and it is unlikely that it will ever be.

However, perhaps you can get what you need by using [`ggnetwork`](https://github.com/briatte/ggnetwork) instead, using the `geom_edgetext` and `geom_edgelabel` geometries together. Take a look at [this vignette](https://briatte.github.io/ggnetwork/) for examples of each geom.
