### ISSUE TITLE
Error: ggnet2 cannot plot multiplex graphs

### ISSUE THREAD

**Issue by jzadra** [briatte/ggnet#32]
I can't find any info on what a multiplex graph is. Additional info on the help / io page would be useful, as my graph looks the same as all the ones on the io page.  I'd like to know what is causing it to be classified as multiplex.

**Comment by WillyWinkel** [comment]
mulitplex apparently says that there can be multiple edges between two nodes. Can be removed for plotting with `simplify(net)`

**Comment by briatte** [comment]
Hi @jzadra 

All apologies for leaving your question unanswered.

@WillyWinkel is correct, 'multiplex' means your graph has multiple edges of different kinds between at least some of its nodes. Passing your graph object to `simplify` does indeed resolve the issue, although I cannot remember right now what it will do to your multiple edges.
