### ISSUE TITLE
adjust edge lengths

### ISSUE THREAD

**Issue by Sanrrone** [briatte/ggnet#36]
Hi, is there a way to adjust manually the distance between nodes?, I'm a bioinformatician and I would like to represent each node as a protein and the edge between proteins would be the similarity. Actually I only can plot the link between them but without any control on edges lengths.

thanks in advance

**Comment by briatte** [comment]
Hi @Sanrrone 

`ggnet2` allows you to modify node placement (which determines the distance between nodes) via its [node placement](https://briatte.github.io/ggnet/#node-placement) argument.

If you need a bit more flexibility, you can try [`ggnetwork`](https://github.com/briatte/ggnetwork) or, for even more options, [`ggraph`](https://github.com/thomasp85/ggraph) -- but all packages will require that you select a node placement algorithm.

One last-resort solution might be to compute the distance between nodes yourself, and to pass that to the network plotting function. [You can do that with `ggnet2`](https://briatte.github.io/ggnet/#using-fixed-placement-coordinates), as well as [with `ggnetwork`](https://briatte.github.io/ggnetwork/#ggnetwork), and probably also with `ggraph`.

Hope this helps!

Best wishes,

François
