### ISSUE TITLE
Self-loop in ggnet

### ISSUE THREAD

**Issue by Melkiades** [briatte/ggnet#41]
Hi! thank you for the amazing work. I was wondering if there is or there will be a plan for plotting self-loops! 

Best,
D.

**Comment by briatte** [comment]
Thanks for your question, @Melkiades.

Unfortunately, there is no easy way to add support for self-loops in `ggnet` (or its successor, [`ggnetwork`](https://github.com/briatte/ggnetwork)). I would recommend instead having a look at @thomasp85's [`ggraph`](https://github.com/thomasp85/ggraph), and in case `ggraph` does not support them either, to `igraph`.

Hope this helps!
