### ISSUE TITLE
Legend for edge.color

### ISSUE THREAD

**Issue by ConGibbs10** [briatte/ggnet#44]
When I input a vector of color values for the edges, I cannot generate a legend which tells the reader what the colored edges represent. This would be a great enhancement.

**Comment by briatte** [comment]
Hi @ConGibbs10 — Indeed, if you pass colours straight to the edges, you cannot label them. For that, you want to pass factors as edge attributes, and then colour (and label) them. I believe the vignette explains how to do that.
