### ISSUE TITLE
ggnet2 does not show Chinese characters

### ISSUE THREAD

**Issue by chentitus** [briatte/ggnet#47]
Hi, I am new to ggnet2. I was working on a token network analysis. I realized that ggnet2 does not show Chinese tokens at all (see the screenshot please). How do I fix it? Any solutions are appreciated!

![Screenshot 2023-03-20 at 10 26 33 AM](https://user-images.githubusercontent.com/125351296/226232618-aad63392-8115-4474-b35c-fc40b521bb16.png)

**Comment by briatte** [comment]
Hi @chentitus

The issue is very likely with the underlying `ggplot2` package. I guess a fix must exist, but you will have to find it in the documentation for that package.

I would also recommend using `ggraph` for a more powerful and up-to-date graphing solution that uses `ggplot2`.
