### ISSUE TITLE
Manual weighting?

### ISSUE THREAD

**Issue by elbamos** [briatte/ggnet#8]
Is there a way, or would you consider adding a way, to set the weighting manually?

I'm trying to construct a network for twitter users who discuss a particular topic.  I'd like to weight each node by the number of people who would see a broadcast from that node.  In twitter-speak, that's the number of "followers."  I could populate my graph with an edge for every follower.  Then it would have 75,000 edges instead of 300, which would create a nasty subsetting problem.  So instead I only keep data for edges between users who've commented on the topic, and I track each user's number of followers.  

Make sense?

**Comment by briatte** [comment]
Hi @elbamos 

I still don't understand exactly what your graph looks like, but if you want to size the nodes of a Twitter network by any numeric value, such as the number of followers of each node, tthe the `ggnet2` function should be able to do exactly what you want:

```{r}
ggnet2(net, size = your_vector_of_weights)
```

or

```{r}
ggnet2(net, size = "a_numeric_vertex_attribute")
```

Have a look at [the vignette](https://briatte.github.io/ggnet/), especially [the part about node sizes](https://briatte.github.io/ggnet/#node-sizes). Hope this helps!

**Comment by elbamos** [comment]
That was from December! I ended up writing new code for visualizing networks using ggplot2, which is an accepted PR to ggally and will be in the next release. If you take a look at some of the examples included there, you'll see what I was trying to accomplish.

**Comment by briatte** [comment]
Would you mind pointing me to the code that you've submitted?

**Comment by elbamos** [comment]
Look at the Dev branch of ggally
