### ISSUE TITLE
node.group is not correct after setting subset.threshold

### ISSUE THREAD

**Issue by qsz13** [briatte/ggnet#9]
Hi, 
after setting the subset.threshold, the group of the nodes seem not correct, here is the code I tested:
n= network(35,directed=FALSE)
type <- sample(1:2, 35, replace=T)
names(type) <- seq(1,35)
ggnet(n,node.group=type,label.nodes = TRUE,subset.threshold =0)
ggnet(n,node.group=type,label.nodes = TRUE,subset.threshold =2)

the group is:
<img width="717" alt="screen shot 2015-08-27 at 10 52 49 am" src="https://cloud.githubusercontent.com/assets/4075761/9511474/cee015f4-4ca9-11e5-9709-bd6e3fd6fdf3.png">

this is the result and the color of some nodes are not correct such as 8, 10, 18 :
<img width="758" alt="screen shot 2015-08-27 at 10 51 18 am" src="https://cloud.githubusercontent.com/assets/4075761/9511454/93d53ad4-4ca9-11e5-9c7e-750c208ed9e9.png">
<img width="750" alt="screen shot 2015-08-27 at 10 47 43 am" src="https://cloud.githubusercontent.com/assets/4075761/9511418/2dcb4512-4ca9-11e5-91f1-8b469bf0253b.png">

**Comment by briatte** [comment]
Yep, that's a bug.

Try replacing lines 120-124 by this, and let me know if it solves the issue:

```r
if(subset.threshold > 0) {
  x = which(sna::degree(net, cmode = weight) < subset.threshold)
  network::delete.vertices(net, x)
  node.group = node.group[ -x ]
}
```

I'm not pushing any patch right now because there's a brand new version of `ggnet` in the works.
